/** Wspólna, ograniczona mapa ikon interfejsu oparta na lucide-react. */
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  BarChart3,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  CircleHelp,
  ClipboardList,
  ContactRound,
  FileText,
  Home,
  Info,
  List,
  ListFilter,
  LogOut,
  Mail,
  Megaphone,
  MousePointerClick,
  PanelTop,
  Phone,
  Plus,
  Send,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Store,
  Users,
  Workflow,
  XCircle,
  type LucideProps,
} from "lucide-react";

const IKONY = {
  alert: AlertCircle,
  blad: XCircle,
  chevronDown: ChevronDown,
  cofniecie: ArrowLeft,
  dokument: FileText,
  formularz: PanelTop,
  info: Info,
  kampania: Megaphone,
  lista: List,
  wyloguj: LogOut,
  odbiorcy: Users,
  pomoc: CircleHelp,
  profil: ContactRound,
  przeglad: Home,
  raport: BarChart3,
  segment: ListFilter,
  sklep: Store,
  ustawienia: Settings,
  uwaga: AlertTriangle,
  wiadomosc: Mail,
  klikniecie: MousePointerClick,
  kalendarz: CalendarDays,
  telefon: Phone,
  wysylka: Send,
  zamowienie: ShoppingBag,
  zgodnosc: ShieldCheck,
  zadania: ClipboardList,
  automatyzacja: Workflow,
  dodaj: Plus,
  gotowe: CheckCircle2,
  check: Check,
} as const;

export type NazwaIkony = keyof typeof IKONY;

export function Icon({ name, ...props }: { name: NazwaIkony } & LucideProps) {
  const Komponent = IKONY[name];
  return <Komponent aria-hidden="true" strokeWidth={1.75} {...props} />;
}
